stages:
  - name: Test
    steps:
      - runScriptConfig:
          image: node:12-slim
          shellScript: |-
            npm install --quiet
            npm audit --audit-level=moderate
            npm run lint
    when:
      branch:
        include:
          - dev
          - staging
      event:
        include:
          - push
  - name: Test Production
    steps:
      - runScriptConfig:
          image: node:12-slim
          shellScript: |-
            npm install --quiet
            npm audit --audit-level=moderate
            npm run lint
    when:
      event:
        include:
          - tag
  - name: Build Image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: devops/tenant:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
          pushRemote: true
          registry: registry.ngaxavilabs.com
    when:
      branch:
        include:
          - dev
          - staging
      event:
        include:
          - push
  - name: Build Image Production
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: devops/tenant:${CICD_GIT_TAG}
          pushRemote: true
          registry: registry.ngaxavilabs.com
    when:
      event:
        include:
          - tag
  - name: Deploy Dev
    steps:
      - applyYamlConfig:
          path: ./k8s/dev-deployment.yaml
    when:
      branch:
        include:
          - dev
      event:
        include:
          - push
  - name: Deploy Staging
    steps:
      - applyYamlConfig:
          path: ./k8s/staging-deployment.yaml
    when:
      branch:
        include:
          - staging
      event:
        include:
          - push
  - name: Deploy Production
    steps:
      - applyYamlConfig:
          path: ./k8s/deployment.yaml
    when:
      event:
        include:
          - tag
notification: {}
