---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  namespace: staging
  labels:
    app: tenant
spec:
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: tenant
  namespace: staging
  labels:
    app: tenant
spec:
  selector:
    app: tenant
  ports:
    - port: 3000
      name: tenant-port
      targetPort: 3000
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: tenant
  namespace: staging
  labels:
    app: tenant
stringData:
  MONGO_USER: tenant-service
  MONGO_PASSWORD: zrtqsTnYKU8q62wPtNzW
type: Opaque

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tenant
  namespace: staging
  labels:
    app: tenant
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - staging.devopsapp.ngaxavilabs.com
      secretName: staging-tenant-ngaxavilabs-com-tls
  rules:
    - hosts: staging.tenant.ngaxavilabs.com
      http:
        paths:
          - path: /api/tenant
            backend:
              serviceName: tenant
              servicePort: 3000
