name: Deploy
on:
  push:
    branches: [dev, staging, master]

jobs:
  build_docker_image_and_deploy:
    name: Build docker image and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

